name: Dev Container Delete Untagged Images

# manual trigger
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "delete-untagged-packages"
  delete-untagged-packages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Dev Container Delete Untagged Images
      # https://github.com/dataaxiom/ghcr-cleanup-action
      # NOTE:
      # Can't use official action
      # https://github.com/actions/delete-package-versions
      # because it doesn't support multi-arch images
      # see: https://github.com/actions/delete-package-versions/issues/90
      - name: Purge untagged devcontainer images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ${{ github.event.repository.name }}-devcontainer
          delete-untagged: true
          token: ${{ secrets.GITHUB_TOKEN }}